# Generated by Django 3.2.5 on 2021-08-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'ITW Product Category',
                'verbose_name_plural': 'ITW Product Categories',
                'db_table': 'itw_product_category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('default_price', models.FloatField(max_length=10, null=True)),
                ('description', models.CharField(max_length=50, null=True)),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('product_category', models.ManyToManyField(related_name='products', to='product.Product_category')),
            ],
            options={
                'verbose_name': 'ITW Product',
                'verbose_name_plural': 'ITW Products',
                'db_table': 'itw_product',
            },
        ),
    ]
